"""${message}

Revision ID: ${up_revision}
Revises: ${down_revision | comma,n}
Create Date: ${create_date}
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
${imports if imports else ""}

# revision identifiers (used by Alembic).
revision: str = ${repr(up_revision)}
down_revision: str | Sequence[str] | None = ${repr(down_revision)}
branch_labels: str | Sequence[str] | None = ${repr(branch_labels)}
depends_on: str | Sequence[str] | None = ${repr(depends_on)}


def upgrade() -> None:
${_clean_commands(upgrades) if upgrades else "    pass"}


def downgrade() -> None:
${_clean_commands(downgrades) if downgrades else "    pass"}

<%!
# Helper function to clean up SQL statements
def _clean_commands(text: str) -> str:
    """
    Remove Alembic auto-generated marker lines from a block of migration commands.

    Args:
        text (str): Multiline string containing Alembic upgrade or downgrade commands.

    Returns:
        str: Cleaned multiline string with marker lines removed, preserving other lines.
    """
    marker_lines = {
        "# ### commands auto generated by Alembic - please adjust! ###",
        "# ### end Alembic commands ###",
    }
    return "\n".join(
        line for line in text.splitlines() if line.strip() not in marker_lines
    )
%>
